name: Render R markdown # name of the github action

# block 1: specify when you want the action to runp
# trigger (github action auto rendering will be triggered by a git push)
on:
  push:
   ## paths:
   ##   - docs/test.Rmd # runs when changes to this document are pushed
        branches: [ main ] # runs when anything is pushed to main
  workflow_dispatch:


# block 2: tell github where the job will be run

jobs:
  render:
    name: Render my document
    runs-on: macOS-latest

# block 3: setup your environment with the following pre-built actions using "uses:" tags
    steps: 
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2

      # create a docs directory in the workflow
      - name: Create docs directory
        run: mkdir -p docs

# block 4: define your actions using "run:" tags, | splits across multiple lines
      - name: Install packages and render the Rmd file
        run: | # add used packages here, put the rendered file into output_dir
          install.packages(c("rmarkdown","tidyverse")) 
          rmarkdown::render("test.Rmd", 
          output_format = "html_document",
          output_dir = "docs" 
          )
        shell: Rscript {0} # R executes the commands directly


      - name: Commit results
        run: |
          git config --global user.name "manu675"
          git config --global user.email "manu675@users.noreply.github.com"
          git add docs/
          git commit -m "Re-build test document" || echo "No changes"
          git push
